version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://whitneyxgunter77:nvEBgqOekiJp4fle@apollonia.ibe9q.mongodb.net/?retryWrites=true&w=majority&appName=apollonia
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: